configfile: "config.yaml"

# Global Variables
REF = config["reference"]
WORKDIR = config["WORKDIR"]
SAMPLES = list(config["samples"].keys())
SIF_DIR = config.get("singularity_image_dir", "/Volumes/X9Pro/container_data/singularity_images")
CONTAINERS = config.get("containers", {})


def container_for(tool):
    """Return the configured Singularity image path for a workflow tool."""
    return CONTAINERS.get(tool, f"{SIF_DIR}/{tool}.sif")


def sample_reads(wildcards, assay):
    """Return one or two FASTQ files for a sample assay.

    Config entries may be a single FASTQ path or a list/tuple containing one
    single-end FASTQ or two paired-end FASTQs. Rejecting other shapes keeps
    aligner command lines predictable.
    """
    reads = config["samples"][wildcards.sample][assay]
    if isinstance(reads, str):
        return [reads]
    if isinstance(reads, (list, tuple)) and len(reads) in (1, 2):
        return list(reads)
    raise ValueError(
        f"samples.{wildcards.sample}.{assay} must be a FASTQ path or a one/two-item FASTQ list"
    )


def get_rna_bam(wildcards):
    """Return the deduplicated RNA BAM produced from a sample's RNA FASTQs."""
    return WORKDIR + f"/dedup/{wildcards.sample}.rna.bam"


rule all:
    input:
        expand(WORKDIR + "/reditools2_dnarna/{sample}.tsv", sample=SAMPLES),
        expand(WORKDIR + "/jacusa2_dnarna/{sample}.out", sample=SAMPLES),
        expand(WORKDIR + "/sprint/{sample}/regular.res", sample=SAMPLES),
        expand(WORKDIR + "/reditools2/{sample}.tsv", sample=SAMPLES),
        expand(WORKDIR + "/deepred/{sample}_predictions.txt", sample=SAMPLES),
        expand(WORKDIR + "/editpredict/{sample}_scores.txt", sample=SAMPLES),
        expand(WORKDIR + "/redinet/{sample}_classified.txt", sample=SAMPLES),
        expand(WORKDIR + "/wgs_coverage/{sample}.cov", sample=SAMPLES),
        expand(WORKDIR + "/germline/{sample}_germline.vcf.gz.tbi", sample=SAMPLES)


include: "preprocessing.smk"
include: "rna_processing.smk"
include: "wgs_processing.smk"
include: "rna_editing.smk"
