import os

# ---------------------------------------------------------------------------
# Reference file generation rules
# ---------------------------------------------------------------------------
# These rules regenerate derived reference files from their raw sources.
# Snakemake only runs them when the output is absent or stale.
# ---------------------------------------------------------------------------

rule generate_simple_repeat:
    """
    Convert raw UCSC simpleRepeat.txt to a sorted, merged BED file.
    Raw format columns: bin, chrom, chromStart, chromEnd, ...
    """
    input:
        config["references"]["simple_repeat_src"]
    output:
        config["references"]["simple_repeat"]
    container: container_for("wgs")
    log:
        stdout="results/logs/generate_simple_repeat.out",
        stderr="results/logs/generate_simple_repeat.err"
    shell:
        r"""
        set -euo pipefail
        awk '{{print $2"\t"$3"\t"$4}}' {input} \
            | bedtools sort \
            | bedtools merge \
            > {output} \
            2> {log.stderr}
        echo "done" > {log.stdout}
        """


rule generate_alu_bed:
    """
    Extract Alu-family elements from RepeatMasker rmsk.txt and merge overlaps.
    rmsk.txt columns: bin, swScore, milliDiv, milliDel, milliIns,
                      genoName, genoStart, genoEnd, genoLeft, strand,
                      repName, repClass, repFamily, ...
    genoName=col6, genoStart=col7, genoEnd=col8 (0-based half-open).
    """
    input:
        config["references"]["rmsk"]
    output:
        config["references"]["alu_bed"]
    container: container_for("wgs")
    log:
        stdout="results/logs/generate_alu_bed.out",
        stderr="results/logs/generate_alu_bed.err"
    shell:
        r"""
        set -euo pipefail
        grep Alu {input} \
            | awk '{{print $6"\t"$7"\t"$8}}' \
            | sort -k1,1 -k2,2n \
            | bedtools merge \
            > {output} \
            2> {log.stderr}
        echo "done" > {log.stdout}
        """


rule build_dbrna_editing:
    """
    Build the three JSON databases consumed by the Morales et al. downstream
    analysis scripts (REDItools2.py, SPRINT.py, JACUSA2.py, etc.).

    Inputs
    ------
    hek_bed    : AG/TC variant BED from WGS alignment (generated by wgs.smk)
    rediportal : REDIportal tab-separated database (GRCh38)
    alu_bed    : Alu element BED (generated by generate_alu_bed)

    Outputs (in config["references"]["db_path"])
    --------------------------------------------
    HEK293T_hg38_clean.json
    REDIportal.json
    Alu_GRCh38.json
    """
    input:
        hek_bed=os.path.join(config["references"]["db_path"], "HEK293T_hg38.bed"),
        rediportal=config["references"]["rediportal_hg38"],
        alu_bed=config["references"]["alu_bed"]
    output:
        hek_json=os.path.join(config["references"]["db_path"], "HEK293T_hg38_clean.json"),
        rediportal_json=os.path.join(config["references"]["db_path"], "REDIportal.json"),
        alu_json=os.path.join(config["references"]["db_path"], "Alu_GRCh38.json")
    log:
        stdout="results/logs/build_dbrna_editing.out",
        stderr="results/logs/build_dbrna_editing.err"
    params:
        script=os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(workflow.snakefile)))),
            "scripts", "build_downstream_dbs.py"
        ),
        outdir=config["references"]["db_path"]
    shell:
        r"""
        set -euo pipefail
        python {params.script} \
            --hek-bed    {input.hek_bed} \
            --rediportal {input.rediportal} \
            --alu        {input.alu_bed} \
            --assembly   hg38 \
            --outdir     {params.outdir} \
            1> {log.stdout} 2> {log.stderr}
        """
